/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#d5e3fc",
        "tertiary-fixed": "#ffdbca",
        "on-background": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed": "#d5e3ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#d8885c",
        "outline": "#737780",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#a7c8ff",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface": "#f7f9fb",
        "secondary": "#515f74",
        "on-surface": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#c3c6d1",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a7c8ff",
        "secondary-fixed-dim": "#b9c7df",
        "secondary-fixed": "#d5e3fc",
        "error-container": "#ffdad6",
        "surface-tint": "#3a5f94",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#723610",
        "inverse-surface": "#2d3133",
        "tertiary": "#381300",
        "surface-variant": "#e0e3e5",
        "primary": "#001e40",
        "on-secondary-fixed": "#0d1c2e",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#57657a",
        "surface-container": "#eceef0",
        "on-primary-fixed-variant": "#1f477b",
        "tertiary-container": "#592300",
        "surface-container-high": "#e6e8ea",
        "on-primary-container": "#799dd6",
        "background": "#f7f9fb",
        "tertiary-fixed-dim": "#ffb690",
        "primary-container": "#003366",
        "on-tertiary-fixed": "#341100",
        "on-surface-variant": "#43474f",
        "on-secondary-fixed-variant": "#3a485b",
        "on-primary-fixed": "#001b3c"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" }
    },
  },
  plugins: [],
}
